name: gamereel
description: A gamified scrollable mini-games app — like Instagram Reels for games.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ── Networking ──────────────────────────────────────────
  http: ^1.2.0

  # ── Local storage ───────────────────────────────────────
  shared_preferences: ^2.2.3

  # ── Animations ──────────────────────────────────────────
  flutter_animate: ^4.5.0

  # ── Fonts ───────────────────────────────────────────────
  google_fonts: ^6.2.1

  # ── State management ────────────────────────────────────
  provider: ^6.1.2

  # ── UUID generator ──────────────────────────────────────
  uuid: ^4.4.0
  supabase_flutter: ^2.10.0

  # ── Social sharing ──────────────────────────────────────
  flutter_svg: ^2.3.0
  share_plus: ^13.1.0
  audioplayers: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # 🔥 App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # 📁 Assets
  assets:
    - assets/images/ScrollX_Logo.png
    - assets/icons/
    - assets/audio/

  fonts:
    - family: National Park
      fonts:
        - asset: assets/fonts/NationalPark/static/NationalPark-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NationalPark/static/NationalPark-Light.ttf
          weight: 300
        - asset: assets/fonts/NationalPark/static/NationalPark-Regular.ttf
          weight: 400
        - asset: assets/fonts/NationalPark/static/NationalPark-Medium.ttf
          weight: 500
        - asset: assets/fonts/NationalPark/static/NationalPark-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NationalPark/static/NationalPark-Bold.ttf
          weight: 700
        - asset: assets/fonts/NationalPark/static/NationalPark-ExtraBold.ttf
          weight: 800

# 🔥 ICON CONFIG (VERY IMPORTANT)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ScrollX_Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ScrollX_Logo.png"
