// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsqYowL-VYZm3cSYYRQ8-FuTMiW3m1zA',
    appId: '1:1069934364668:web:9b095c48408136c537d479',
    messagingSenderId: '1069934364668',
    projectId: 'gamereelb',
    authDomain: 'gamereelb.firebaseapp.com',
    storageBucket: 'gamereelb.firebasestorage.app',
    measurementId: 'G-1TTX4L7KDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwUralxYihhCzyreuriFuans2SIpGrDlo',
    appId: '1:1069934364668:android:976322d42e26d47037d479',
    messagingSenderId: '1069934364668',
    projectId: 'gamereelb',
    storageBucket: 'gamereelb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Ia-q-Nq2gTuqns5FBjDqbTa8KPNKoa0',
    appId: '1:1069934364668:ios:03c12181946641cb37d479',
    messagingSenderId: '1069934364668',
    projectId: 'gamereelb',
    storageBucket: 'gamereelb.firebasestorage.app',
    iosBundleId: 'com.example.gamereelb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Ia-q-Nq2gTuqns5FBjDqbTa8KPNKoa0',
    appId: '1:1069934364668:ios:03c12181946641cb37d479',
    messagingSenderId: '1069934364668',
    projectId: 'gamereelb',
    storageBucket: 'gamereelb.firebasestorage.app',
    iosBundleId: 'com.example.gamereelb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcsqYowL-VYZm3cSYYRQ8-FuTMiW3m1zA',
    appId: '1:1069934364668:web:7a55b84e8b0e124537d479',
    messagingSenderId: '1069934364668',
    projectId: 'gamereelb',
    authDomain: 'gamereelb.firebaseapp.com',
    storageBucket: 'gamereelb.firebasestorage.app',
    measurementId: 'G-JZ3PCLMZCG',
  );

}