// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';

// ── Uncomment after Firebase setup ──────────────────────────────────────────
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';   // generated by: flutterfire configure

import 'core/app_theme.dart';
import 'screens/feed_screen.dart';
import 'screens/leaderboard_screen.dart';
import 'screens/profile_screen.dart';
import 'services/user_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait
  await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp]);

  // Status bar: transparent with light icons
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:          Colors.transparent,
    statusBarIconBrightness: Brightness.light,
  ));

  // ── Firebase init — uncomment after adding google-services.json ──────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => UserProvider()..initialize(),
      child: const GameReelApp(),
    ),
  );
}

// ── Root widget ───────────────────────────────────────────────────────────────
class GameReelApp extends StatelessWidget {
  const GameReelApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: AppConstants.appName,
    theme: AppTheme.theme,
    debugShowCheckedModeBanner: false,
    home: const MainShell(),
  );
}

// ── Bottom-nav shell ──────────────────────────────────────────────────────────
class MainShell extends StatefulWidget {
  const MainShell({super.key});
  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _idx = 0;

  static const _screens = [
    FeedScreen(),
    LeaderboardScreen(),
    ProfileScreen(),
  ];

  void _onTap(int i) {
    HapticFeedback.selectionClick();
    setState(() => _idx = i);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    body: IndexedStack(index: _idx, children: _screens),
    bottomNavigationBar: _BottomNav(current: _idx, onTap: _onTap),
  );
}

// ── Custom bottom navigation bar ──────────────────────────────────────────────
class _BottomNav extends StatelessWidget {
  final int    current;
  final ValueChanged<int> onTap;
  const _BottomNav({required this.current, required this.onTap});

  @override
  Widget build(BuildContext context) => Container(
    decoration: const BoxDecoration(
      color: AppTheme.bgCard,
      border: Border(top: BorderSide(
          color: AppTheme.border, width: 0.5)),
    ),
    child: SafeArea(
      child: SizedBox(
        height: 56,
        child: Row(children: [
          _Item(icon: Icons.play_circle_outline,
              active: Icons.play_circle_filled,
              label: 'Feed', idx: 0, current: current, onTap: onTap),
          _Item(icon: Icons.emoji_events_outlined,
              active: Icons.emoji_events,
              label: 'Ranks', idx: 1, current: current, onTap: onTap),
          _Item(icon: Icons.person_outline,
              active: Icons.person,
              label: 'Profile', idx: 2, current: current, onTap: onTap),
        ]),
      ),
    ),
  );
}

class _Item extends StatelessWidget {
  final IconData icon;
  final IconData active;
  final String   label;
  final int      idx;
  final int      current;
  final ValueChanged<int> onTap;

  const _Item({
    required this.icon, required this.active,
    required this.label, required this.idx,
    required this.current, required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final on = idx == current;
    return Expanded(
      child: GestureDetector(
        onTap: () => onTap(idx),
        behavior: HitTestBehavior.opaque,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            AnimatedSwitcher(
              duration: const Duration(milliseconds: 200),
              child: Icon(on ? active : icon,
                  key: ValueKey(on),
                  color: on ? AppTheme.accent : AppTheme.textMuted,
                  size: 24),
            ),
            const SizedBox(height: 3),
            Text(label, style: TextStyle(
              color: on ? AppTheme.accent : AppTheme.textMuted,
              fontSize: 10,
              fontWeight: on ? FontWeight.w600 : FontWeight.w400,
            )),
          ],
        ),
      ),
    );
  }
}
