// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';

// ── Uncomment after Firebase setup ──────────────────────────────────────────
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';   // generated by: flutterfire configure

import 'core/app_theme.dart';
import 'screens/feed_screen.dart';
import 'screens/leaderboard_screen.dart';
import 'screens/profile_screen.dart';
import 'services/user_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait
  await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp]);

  // Status bar: transparent with light icons
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:          Colors.transparent,
    statusBarIconBrightness: Brightness.light,
  ));

  // ── Firebase init — uncomment after adding google-services.json ──────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    ChangeNotifierProvider(
      create: (_) => UserProvider()..initialize(),
      child: const GameReelApp(),
    ),
  );
}

// ── Root widget ───────────────────────────────────────────────────────────────
class GameReelApp extends StatelessWidget {
  const GameReelApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
    title: AppConstants.appName,
    theme: AppTheme.theme,
    debugShowCheckedModeBanner: false,
    home: const MainShell(),
  );
}

// ── Bottom-nav shell ──────────────────────────────────────────────────────────
class MainShell extends StatefulWidget {
  const MainShell({super.key});
  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _idx = 0;

  static const _screens = [
    FeedScreen(),
    LeaderboardScreen(),
    ProfileScreen(),
  ];

  void _onTap(int i) {
    HapticFeedback.selectionClick();
    setState(() => _idx = i);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    body: IndexedStack(index: _idx, children: _screens),
    bottomNavigationBar: _BottomNav(current: _idx, onTap: _onTap),
  );
}

// ── Custom bottom navigation bar ──────────────────────────────────────────────
class _BottomNav extends StatelessWidget {
  final int current;
  final ValueChanged<int> onTap;
  const _BottomNav({required this.current, required this.onTap});

  @override
  Widget build(BuildContext context) => Container(
        decoration: BoxDecoration(
          color: const Color(0xFF100E24),
          border: Border(
            top: BorderSide(color: Colors.white.withOpacity(0.08), width: 1),
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.28),
              blurRadius: 18,
              offset: const Offset(0, -6),
            ),
          ],
        ),
        child: SafeArea(
          top: false,
          child: SizedBox(
            height: 66,
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
              child: Row(children: [
                _Item(
                  icon: Icons.play_circle_outline,
                  active: Icons.play_circle_filled,
                  label: 'Feed',
                  idx: 0,
                  current: current,
                  color: AppTheme.accent,
                  onTap: onTap,
                ),
                _Item(
                  icon: Icons.emoji_events_outlined,
                  active: Icons.emoji_events,
                  label: 'Ranks',
                  idx: 1,
                  current: current,
                  color: AppTheme.gold,
                  onTap: onTap,
                ),
                _Item(
                  icon: Icons.person_outline,
                  active: Icons.person,
                  label: 'Profile',
                  idx: 2,
                  current: current,
                  color: AppTheme.teal,
                  onTap: onTap,
                ),
              ]),
            ),
          ),
        ),
      );
}

class _Item extends StatelessWidget {
  final IconData icon;
  final IconData active;
  final String label;
  final int idx;
  final int current;
  final Color color;
  final ValueChanged<int> onTap;

  const _Item({
    required this.icon,
    required this.active,
    required this.label,
    required this.idx,
    required this.current,
    required this.color,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final on = idx == current;
    return Expanded(
      child: GestureDetector(
        onTap: () => onTap(idx),
        behavior: HitTestBehavior.opaque,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 220),
          curve: Curves.easeOutCubic,
          height: 52,
          margin: const EdgeInsets.symmetric(horizontal: 4),
          decoration: BoxDecoration(
            color: on ? color.withOpacity(0.14) : Colors.transparent,
            borderRadius: BorderRadius.circular(18),
            border: Border.all(
              color: on ? color.withOpacity(0.28) : Colors.transparent,
            ),
          ),
          child: Stack(children: [
            Align(
              alignment: Alignment.topCenter,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 220),
                curve: Curves.easeOutCubic,
                width: on ? 20 : 0,
                height: 3,
                decoration: BoxDecoration(
                  color: color,
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
            Center(
              child: TweenAnimationBuilder<double>(
                tween: Tween<double>(end: on ? 1 : 0),
                duration: const Duration(milliseconds: 260),
                curve: Curves.easeOutBack,
                builder: (context, pop, child) => Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Transform.translate(
                      offset: Offset(0, -5 * pop),
                      child: Transform.scale(
                        scale: 1 + (0.10 * pop),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 220),
                          curve: Curves.easeOutCubic,
                          width: 30,
                          height: 30,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: on ? color.withOpacity(0.18) : Colors.transparent,
                            boxShadow: on
                                ? [
                                    BoxShadow(
                                      color: color.withOpacity(0.22),
                                      blurRadius: 12,
                                      offset: const Offset(0, 4),
                                    ),
                                  ]
                                : null,
                          ),
                          child: AnimatedSwitcher(
                            duration: const Duration(milliseconds: 180),
                            transitionBuilder: (child, animation) => FadeTransition(
                              opacity: animation,
                              child: ScaleTransition(scale: animation, child: child),
                            ),
                            child: Icon(
                              on ? active : icon,
                              key: ValueKey('$label-$on'),
                              color: on ? color : AppTheme.textMuted,
                              size: on ? 22 : 21,
                            ),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 1),
                    AnimatedDefaultTextStyle(
                      duration: const Duration(milliseconds: 180),
                      style: TextStyle(
                        color: on ? color : AppTheme.textMuted,
                        fontSize: 10,
                        fontWeight: on ? FontWeight.w700 : FontWeight.w500,
                      ),
                      child: Text(label),
                    ),
                  ],
                ),
              ),
            ),
          ]),
        ),
      ),
    );
  }
}
